# Generated by Django 5.0.6 on 2026-06-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='cycle_start_day',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
