# Generated by Django 5.0.6 on 2026-05-30 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_transaction_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='external_id',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
    ]
