# Generated by Django 5.0.6 on 2026-06-01 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0002_recurringtransaction_credit'),
        ('transactions', '0003_alter_transaction_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='recurring_transaction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_transactions', to='recurring.recurringtransaction'),
        ),
    ]
