# Generated by Django 6.0.6 on 2026-06-05 05:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_credit_fields'),
        ('categories', '0002_categoryrule'),
        ('recurring', '0002_recurringtransaction_credit'),
        ('transactions', '0004_transaction_recurring_transaction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='tx_account_date_idx'),
        ),
    ]
