# Generated by Django 6.0.5 on 2026-06-07 19:25

from django.db import migrations


def deactivate_credit_linked(apps, schema_editor):
    """Le crédit est désormais la source unique de sa mensualité.

    Les récurrences liées à un crédit sont devenues redondantes : on les
    désactive pour qu'elles ne soient plus comptées ni affichées. Réversible
    et sans perte (le lien `credit` est conservé).
    """
    RecurringTransaction = apps.get_model('recurring', 'RecurringTransaction')
    RecurringTransaction.objects.filter(credit__isnull=False, is_active=True).update(is_active=False)


def noop_reverse(apps, schema_editor):
    # Pas de réactivation automatique : on ne sait pas lesquelles étaient
    # actives avant. L'utilisateur peut les réactiver manuellement si besoin.
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('recurring', '0002_recurringtransaction_credit'),
    ]

    operations = [
        migrations.RunPython(deactivate_credit_linked, noop_reverse),
    ]
