# Generated by Django 5.0.6 on 2026-06-01 21:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_import_ignored',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='account',
            name='linked_credit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accounts', to='credits.credit'),
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('checking', 'Courant'), ('savings', 'Épargne'), ('cash', 'Espèces'), ('credit', 'Crédit'), ('other', 'Autre')], default='checking', max_length=20),
        ),
    ]
