# Generated by Django 6.0.5 on 2026-06-07 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_account_credit_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='exclude_from_total',
            field=models.BooleanField(default=False),
        ),
    ]
