# Generated by Django 5.0.6 on 2026-06-02 05:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credits', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='max_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='credit_type',
            field=models.CharField(choices=[('mortgage', 'Immobilier'), ('auto', 'Auto'), ('consumer', 'Consommation'), ('revolving', 'Revolving'), ('other', 'Autre')], default='consumer', max_length=20),
        ),
        migrations.AlterField(
            model_name='credit',
            name='duration_months',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='initial_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='monthly_payment',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='credit',
            name='remaining_capital',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.CreateModel(
            name='CreditDraw',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('monthly_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('duration_months', models.IntegerField()),
                ('start_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('credit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='draws', to='credits.credit')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
