# Generated by Django 6.0.5 on 2026-06-07 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_account_exclude_from_total'),
        ('credits', '0002_credit_revolving_draw'),
    ]

    operations = [
        migrations.AddField(
            model_name='credit',
            name='payment_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credits_drawn', to='accounts.account'),
        ),
        migrations.AddField(
            model_name='credit',
            name='payment_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
